### PR TITLE
Add build instructions for Linux

### PR DESCRIPTION
**Pull request by frost-nzcr4**
Installation might be not so obvious for non Java developers and possibly related to #25 issue.

### CODE REVIEW

**Comment by mishoo** [comment]
I followed these steps (almost; the `wget` commands didn't work and I had to download the JRE files from Oracle using a browser, so that I can click their "Accept terms 'n shit").  Next, the build went successfully and I (think I) have all the files in `../Deploy`.  However, I'm now stuck with this:

```
Running as root.
Used java home : ./x10flasher_lib/linjre64
Error: Could not find or load main class gui.Main
```

I'm not a Java developer and have no idea how to fix this...  I assume it's a trivial issue, though.  Any help would be very appreciated!

**Comment by frost-nzcr4** [comment]
There is should be /Deploy/FlashTool/x10flasher.jar file that created with command `ant -buildfile ant/setup-linux.xml binaries`

**Comment by mishoo** [comment]
That must be the problem.  That file exists, but it's empty:

```
$ ls -l ../Deploy/FlashTool/x10flasher.jar
-rw-rw-r-- 1 mishoo mishoo 809 sep 25 13:27 ../Deploy/FlashTool/x10flasher.jar
````

I checked and it only contains the `META-INF` directory, nothing more.

**Comment by frost-nzcr4** [comment]
Did you create `bin` subfolder at Flashtool source folder?
After command `ant -buildfile ant/setup-linux.xml binaries` I've got this output (look at `main_lib` section):

```ShellSession
Buildfile: ~/Downloads/Flashtool/ant/setup-linux.xml

clean:
   [delete] Deleting directory ~/Downloads/Deploy/FlashTool/x10flasher_lib/swtwin
   [delete] Deleting directory ~/Downloads/Deploy/FlashTool/x10flasher_lib/swtmac
   [delete] Deleting directory ~/Downloads/Deploy/FlashTool/drivers

loadprops:

main_lib:
      [jar] Building jar: ~/Downloads/Deploy/FlashTool/x10flasher.jar

JRE:
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool/x10flasher_lib/linjre32/lib/security
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool/x10flasher_lib/linjre32/lib/security
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool/x10flasher_lib/linjre64/lib/security
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool/x10flasher_lib/linjre64/lib/security

binaries:
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool
     [copy] Copying 1 file to ~/Downloads/Deploy/FlashTool/x10flasher_lib
     [copy] Copying 12 files to ~/Downloads/Deploy/FlashTool/x10flasher_lib

BUILD SUCCESSFUL
Total time: 5 seconds
```

**Comment by MartinX3** [comment]
Same problem here.
Ubuntu 18.04
I followed every step in the build instructions.

ant -version
Apache Ant(TM) version 1.10.3 compiled on March 29 2018

By the way, why is the "bin"-folder empty?

**Pull request merged**
